### ISSUE TITLE
代码过长导致样式显示残缺

### ISSUE THREAD

**Issue by flower1360** [mosszzom/cnblogs-theme-hacker#2]
> 问题描述

![image](https://user-images.githubusercontent.com/64666574/95699827-1867d980-0c78-11eb-8851-f3de8a9e1d22.png)

像上面这样, 顶部的样式看起来像丢失了, 希望下个一版本可以解决这个问题

**Comment by ZeerBeer** [comment]
事实上, 我已经注意到了这个问题, 之后的提交会解决这一问题.

**Comment by ZeerBeer** [comment]
现在它变了了这样, 希望你能喜欢.

![image](https://user-images.githubusercontent.com/64666574/95701804-1fddb180-0c7d-11eb-8c03-62f4ac20f1fd.png)

**Comment by mosszzom** [comment]
see https://github.com/mosszzom/cnblogs-theme-hacker/issues/10#issue-1006930299
