### ISSUE TITLE
暗黑模式下的html表格

### ISSUE THREAD

**Issue by 4thrun** [mosszzom/cnblogs-theme-hacker#9]
^_^试用了您开发的主题，发现暗黑模式下的html表格的<th>标签没有转换颜色![image](https://user-images.githubusercontent.com/65476356/106010857-debac180-60f4-11eb-8869-96cee92eb209.jpeg)

**Comment by ZeerBeer** [comment]
近期会做出修复: 

- [ ] 暗黑模式下的html表格的标签没有转换颜色

**Comment by mosszzom** [comment]
see https://github.com/mosszzom/cnblogs-theme-hacker/issues/10#issue-1006930299
